import * as fs from "fs";
import * as path from "path";

export interface ConsultantBriefInput {
  businessGoal: string;
  keyTakeaways: string[];
  findingsBySection: Array<{
    title: string;
    description: string;
    charts?: string[];
  }>;
  prescriptiveRecommendations: Array<{
    action: string;
    expectedImpact: string;
    priority: "HIGH" | "MEDIUM" | "LOW";
  }>;
  dataQualityNotes?: string[];
}

export function generateExecutiveBrief(
  input: ConsultantBriefInput,
  repoRoot: string
): { reportPath: string; markdownContent: string } {
  const reportsDir = path.join(repoRoot, "outputs", "reports");
  fs.mkdirSync(reportsDir, { recursive: true });

  const dateStr = new Date().toISOString().split("T")[0];
  const filename = `executive_brief_${dateStr}.md`;
  const reportPath = path.join(reportsDir, filename);

  let md = `# 📊 Executive Data Science Brief: ${input.businessGoal}\n\n`;
  md += `**Generated By:** DataForge AI (Autonomous Data Science Partner)\n`;
  md += `**Date:** ${dateStr}\n\n`;
  md += `---\n\n`;

  md += `## ⏱️ 30-Second Executive Summary\n\n`;
  for (const takeaway of input.keyTakeaways) {
    md += `* **${takeaway}**\n`;
  }
  md += `\n---\n\n`;

  md += `## 🔍 Key Findings & Diagnostic Evidence\n\n`;
  for (const section of input.findingsBySection) {
    md += `### ${section.title}\n\n`;
    md += `${section.description}\n\n`;
    if (section.charts && section.charts.length > 0) {
      for (const chart of section.charts) {
        const relativeChartPath = chart.startsWith("outputs/") ? chart.replace(/^outputs\//, "../") : chart;
        md += `![${section.title} Chart](${relativeChartPath})\n\n`;
      }
    }
  }
  md += `---\n\n`;

  md += `## 🎯 Prescriptive Recommendations & Action Plan\n\n`;
  md += `| Priority | Recommended Action | Expected Business Impact |\n`;
  md += `| :--- | :--- | :--- |\n`;
  for (const rec of input.prescriptiveRecommendations) {
    const badge = rec.priority === "HIGH" ? "🔴 HIGH" : rec.priority === "MEDIUM" ? "🟡 MEDIUM" : "🟢 LOW";
    md += `| **${badge}** | ${rec.action} | ${rec.expectedImpact} |\n`;
  }
  md += `\n---\n\n`;

  if (input.dataQualityNotes && input.dataQualityNotes.length > 0) {
    md += `## 🛡️ Data Integrity & Methodology Notes\n\n`;
    for (const note of input.dataQualityNotes) {
      md += `* *${note}*\n`;
    }
    md += `\n`;
  }

  fs.writeFileSync(reportPath, md, "utf-8");

  return {
    reportPath: path.relative(repoRoot, reportPath),
    markdownContent: md
  };
}
